server:
  port: 8000

spring:
  application:
    name: db_project
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_project?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
